name: CI
on: [push, pull_request]

jobs:
  lint:
    name: âœ”ï¸ Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run lint

  check-formatting:
    name: âœ”ï¸ Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run format:check

  build:
    name: ğŸ› ï¸ Build
    runs-on: ubuntu-latest
    needs:
      - lint
      - check-formatting
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
